APP_URL: https://beispiel.de
APP_BASE_PATH: ""

LEBENSLAUF_DATEN_PFAD: .local/lebenslauf
LEBENSLAUF_YAML_PFAD: ""
LEBENSLAUF_JSON_PFAD: var/tmp/lebenslauf.json
LEBENSLAUF_PUBLIC_PROFILE: default
LEBENSLAUF_LANG_DEFAULT: de
LEBENSLAUF_LANGS: "de,en"
